CREATE SCHEMA LOGIN;

CREATE TABLE LOGIN.LISTUSER
(
	USER_ID VARCHAR(25) NOT NULL,
	PASSWD VARCHAR(8) NOT NULL,
	LNAME VARCHAR(10),
	FNAME VARCHAR(10),
	ADDR VARCHAR(50),
	Q1_DOB DATE,
	Q2_CITY VARCHAR(25),
	Q3_NAME VARCHAR(25),
	PRIMARY KEY (USER_ID)
);


CREATE TABLE LOGIN.COMMENTS
(
	USER_ID VARCHAR(25) NOT NULL,
	NAME VARCHAR(10),
	COMMENT VARCHAR(50),
	COMMENT_DT DATE
)

INSERT INTO LOGIN.LISTUSER VALUES ('admin@gmail.com','admin123','admin','test',' chicago,IL','09/07/1987','iit','itm');
INSERT INTO LOGIN.LISTUSER VALUES ('test@gmail.com','test1234','test','test','chicago,IL','09/07/1988','iit','itm');
INSERT INTO LOGIN.LISTUSER VALUES ('shafi@gmail.com','abcd1234','ulla','shafi','chicago,IL','09/07/1989','Bangalore','kamala');



